name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    if: ${{github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)}}

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
      - name: Install
        run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --prefix ${{github.workspace}}/install

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: REFramework-D2D
          path: ${{github.workspace}}/install/bin/*
          if-no-files-found: error
          
      - name: Compress artifacts
        uses: vimtor/action-zip@v1.2
        with:
          files: install/bin/
          dest: REFramework-D2D.zip
      
      - name: Release
        uses: softprops/action-gh-release@v2.0.4
        if: ${{startsWith(github.ref, 'refs/tags/')}}
        with:
          files: ${{github.workspace}}/REFramework-D2D.zip
          
